### ISSUE TITLE
Error de reproducción

### ISSUE THREAD

**Issue by MusicaFM** [balandro-tk/balandro#2]
Hola equipo balandro. Hay ocasiones que eliges un determinado capítulo, y un servidor por ejemplo Gamovideo, y a veces va el mismo enlace y otras veces no, osea aleatoriamente puede que reproduzca y otras veces da error y no reproduce nada, hay que estar reintentándolo hasta que te canses o se reproduzca. Pasa con todos los servidores y páginas que tenéis asociadas a Balandro y antes funcionaba de lujo, pero desde hace unas semanas ya funciona cuando quiere. Otra cosa, Playdede no funciona en Balandro, pongo y activo mi user y pass en el apartado cuentas y no me saca ni un capítulo. ¿Solución? Gracias

**Comment by darkozma** [comment]
Este tipo de errores suelen solucionarse con nuevas versiones y sus fix.
Puedes dirigirte a este grupo de telegram para reportar dichos errores y estar atento a lo que acontece:
https://t.me/balandroasesor

**Comment by darkozma** [comment]
Procedo al cierre de este hilo, ya que no se ha recibido respuesta.
Si sigue interesado, puede abrir un nuevo 'issue'.
